version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t indra .
      - docker tag indra:latest 292075781285.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/indra:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 292075781285.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/indra:latest
